name: sandwich_shop
description: A Flutter application for a sandwich shop.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
  assets:
	- assets/images/logo.png
	- assets/images/veggieDelight_footlong.png
	- assets/images/veggieDelight_six_inch.png
	- assets/images/chickenTeriyaki_footlong.png
	- assets/images/chickenTeriyaki_six_inch.png
	- assets/images/tunaMelt_footlong.png
	- assets/images/tunaMelt_six_inch.png
	- assets/images/meatballMarinara_footlong.png
	- assets/images/meatballMarinara_six_inch.png
